


body 
{
    background-color:#f0f2f5;
    font-family: Arial, Helvetica, sans-serif;
    text-align: center;
}
.main_title{
    text-align: center;
    color:#4267B2;
    margin-top:20px;
}
.content{
    text-align: center;
    margin-top:10px;
    padding-bottom:10px;
}
.card-box{
    background: #fff;
    box-shadow: 0 0 13px 0 silver;
    border-radius: 5px;
    padding:30px 0px;
    width:90%;
    margin:0 auto;
    padding-top:40px;
    
} 
.detail{
    padding: 10px;
    border: thin solid silver;
    margin:7px;
    width:67%;
    transform: 0.5s;
    font-size: 15px;
}
.login{
    color:#fff;
    background:#1877f2;
    border: none;
    border-radius: 6px;
    padding:10px;
    width:74%;
    font-size: 15px;
    margin:8px;
    font-weight:700;
}
.for-password{
    border:none;
    color:#1877fb;
    margin:8px;
    background:white;
}
.new-account{
    color:#fff;
    background:#42b724;
    border:none;
    padding:10px;
    border-radius:6px;
    width:74%;
    font-size: 15px;
    margin:8px;
    font-weight:700;
}
.last-content{
    padding-top:10px;
}



























i






